buildscript {
    repositories {
        **ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.0'
        **BUILD_SCRIPT_DEPS**
    }
}

// We do NOT need an 'allprojects' block here anymore because
// settingsTemplate.gradle handles it for every module.

task clean(type: Delete) {
    delete rootProject.buildDir
}